language: haskell

ghc:
    - 7.8
    - 7.6

install:
    - cabal install --enable-tests --only-dependencies hspec-expectations-lens.cabal

script:
    - cabal install --enable-tests hspec-expectations-lens.cabal
    - cabal sdist && cabal install --enable-tests dist/hspec-expectations-lens-*.tar.gz
